/* Generated by backend/agent_dashboard_api from data/reports/agent_dashboard.json. */
window.AGENT_DATA = {
  "meta": {
    "projectName": "design-studio-lead-engine",
    "companyName": "Вектор Плюс-Про",
    "overallStatus": "OK",
    "currentStage": "2026-05-17 — Подключён Агент безопасности как контрольный слой системы",
    "generatedAt": "2026-05-16T23:17:05Z",
    "nextSmallStep": "открыть `data/reports/agent_dashboard.html` и глазами проверить новый блок `Security Agent Control Layer` рядом с управленческими блоками.",
    "sourceReport": "data/reports/agent_dashboard.json",
    "dataMode": "live-local-dashboard-json"
  },
  "summary": {
    "channelsTotal": 17,
    "wave1Channels": 9,
    "artifactsCount": 29,
    "servicesCount": 7,
    "agentsCount": 6,
    "subrolesCount": 33,
    "visualNodesCount": 47
  },
  "accent": {
    "cyan": "#4DE3FF",
    "green": "#66F2A6",
    "amber": "#F6C85F",
    "red": "#FF5C7A",
    "violet": "#A6B0FF",
    "grey": "#8E9AAA"
  },
  "orchestrator": {
    "id": "orchestrator",
    "label": "AI Orchestrator",
    "type": "orchestrator",
    "sublabel": "CLAUDE.md · AGENTS.md · REPORT.md",
    "x": 1180,
    "y": 230,
    "w": 360,
    "h": 150,
    "accent": "#4DE3FF",
    "status": "active",
    "statusLabel": "OK",
    "description": "Главный управляющий слой проекта. Он принимает задачу от человека, маршрутизирует её в нужный агентский отдел, проверяет ограничения и фиксирует результат в REPORT.md.",
    "responsibilities": [
      "Принять задачу от человека",
      "Определить нужный агентский отдел",
      "Проверить safety locks и правила проекта",
      "Получить agent-result или task-handoff",
      "Обновить память проекта и следующий шаг"
    ],
    "inputs": [
      "Human task",
      "REPORT.md",
      "AGENTS.md",
      "CLAUDE.md",
      "Agent reports"
    ],
    "outputs": [
      "task-handoff",
      "agent-result",
      "checker verdict",
      "REPORT.md update"
    ],
    "tools": [
      "CLAUDE.md",
      "AGENTS.md",
      "REPORT.md",
      "scripts/check_agent_okr_contract.py"
    ],
    "statusStates": [
      "Reading REPORT.md",
      "Routing task",
      "Checking quality",
      "Awaiting approval",
      "Updating memory"
    ]
  },
  "agents": [
    {
      "id": "a1-scout",
      "dashboardAgentId": "agent1_scout",
      "label": "Agent 1 · Scout",
      "short": "A1",
      "type": "agent",
      "department": "Разведка источников",
      "x": 560,
      "y": 540,
      "w": 320,
      "h": 188,
      "accent": "#4DE3FF",
      "status": "waiting",
      "statusLabel": "planned/manual",
      "description": "Ищет, где могут появляться будущие заказчики и какие темы важны рынку.",
      "readiness": 35,
      "krReadiness": 67,
      "stats": [
        {
          "k": "Покрытие карты ист…",
          "v": "17/17 каналов"
        },
        {
          "k": "subroles",
          "v": "5"
        },
        {
          "k": "skills",
          "v": "4"
        },
        {
          "k": "status",
          "v": "planned/manual"
        }
      ],
      "responsibilities": [
        "Market Research Agent: рыночный спрос, сегменты, темы → SignalCard",
        "Competitor Analyst: конкуренты, упаковка, доказательства → competitor_note",
        "Source Radar: новые каналы лидов и контента → source_signal_card",
        "Reviews/Maps Monitor: карты, отзывы, вопросы клиентов → review_signal",
        "Demand Signal Curator: отбор сигналов и handoff → handoff_recommendation"
      ],
      "inputs": [
        "рынок",
        "конкуренты",
        "отзывы",
        "карты",
        "тендерные площадки"
      ],
      "outputs": [
        "source cards для Agent 2",
        "темы и боли для Agent 4",
        "каналы для Agent 5"
      ],
      "sources": [
        "Смотрит весь рынок: 17 системных каналов, конкурентов, каналы Яники и backlog-источники.",
        "primary: Gmail tenders",
        "primary: Telegram chats",
        "primary: Outbound manual",
        "primary: Avito",
        "primary: Profi.ru",
        "primary: Yandex Services",
        "primary: +11 ещё",
        "watchlist: {'source_id': 'tg_prozru', 'source_name': 'Проектирование зданий', 'source_url': 'https://t.me/prozru', 'platform': 'telegram', 'segment': 'B', 'source_type': 'channel', 'owner_agent': 'agent1_scout', 'status': 'active_manual', 'why_watch': 'B2B-аудитория проектировщиков ГИПов и руководителей проектных компаний'}",
        "watchlist: {'source_id': 'tg_rupor_gip', 'source_name': 'Рупор ГИП', 'source_url': 'https://t.me/rupor_project', 'platform': 'telegram', 'segment': 'B', 'source_type': 'channel', 'owner_agent': 'agent1_scout', 'status': 'active_manual', 'why_watch': 'Новости нормы и проектная документация для ГИПов'}",
        "watchlist: {'source_id': 'tg_gipkurs_chat', 'source_name': 'ПРОЕКТИРОВАНИЕ ЗДАНИЙ ЧАТ', 'source_url': 'https://t.me/GIPkurs', 'platform': 'telegram', 'segment': 'B', 'source_type': 'chat', 'owner_agent': 'agent1_scout', 'status': 'planned_manual', 'why_watch': 'Чат проектировщиков и вакансий как источник боли и спроса'}",
        "watchlist: {'source_id': 'tg_pereplan_one', 'source_name': 'PEREPLAN. Перепланировка и согласование', 'source_url': 'https://t.me/pereplan_one', 'platform': 'telegram', 'segment': 'A', 'source_type': 'channel', 'owner_agent': 'agent1_scout', 'status': 'active_manual', 'why_watch': 'Крупный B2C/B2B канал по перепланировкам Москвы и Петербурга'}",
        "watchlist: {'source_id': 'tg_pereplan_mos_mo', 'source_name': 'Согласование перепланировки в Москве и МО', 'source_url': 'https://t.me/pereplan_mos_mo', 'platform': 'telegram', 'segment': 'A', 'source_type': 'channel', 'owner_agent': 'agent1_scout', 'status': 'active_manual', 'why_watch': 'Узкая аудитория дизайнеров ремонтников риелторов'}",
        "watchlist: {'source_id': 'site_mostpr', 'source_name': 'МОСтройпроект', 'source_url': 'https://mostpr.ru/', 'platform': 'website', 'segment': 'A', 'source_type': 'competitor_site', 'owner_agent': 'agent1_scout', 'status': 'active_manual', 'why_watch': 'Сильная упаковка с кейсами сроками стоимостью и документами'}",
        "watchlist: +9 ещё",
        "yanika: {'source_id': 'yanika_channel_001', 'source_name': '', 'source_url': '', 'platform': 'telegram|vk|max|dzen|website|other', 'segment': 'A|B|A+B', 'source_type': '', 'owner_agent': 'agent1_scout', 'status': 'pending_yanika_input', 'why_watch': ''}",
        "yanika: {'source_id': 'yanika_channel_002', 'source_name': '', 'source_url': '', 'platform': 'telegram|vk|max|dzen|website|other', 'segment': 'A|B|A+B', 'source_type': '', 'owner_agent': 'agent1_scout', 'status': 'pending_yanika_input', 'why_watch': ''}",
        "yanika: {'source_id': 'yanika_channel_003', 'source_name': '', 'source_url': '', 'platform': 'telegram|vk|max|dzen|website|other', 'segment': 'A|B|A+B', 'source_type': '', 'owner_agent': 'agent1_scout', 'status': 'pending_yanika_input', 'why_watch': ''}",
        "yanika: {'source_id': 'yanika_channel_004', 'source_name': '', 'source_url': '', 'platform': 'telegram|vk|max|dzen|website|other', 'segment': 'A|B|A+B', 'source_type': '', 'owner_agent': 'agent1_scout', 'status': 'pending_yanika_input', 'why_watch': ''}",
        "yanika: {'source_id': 'yanika_channel_005', 'source_name': '', 'source_url': '', 'platform': 'telegram|vk|max|dzen|website|other', 'segment': 'A|B|A+B', 'source_type': '', 'owner_agent': 'agent1_scout', 'status': 'pending_yanika_input', 'why_watch': ''}",
        "backlog: 2GIS как отдельный lead/referrer source",
        "backlog: VK-группы и обсуждения",
        "backlog: коммерческие тендерные площадки",
        "backlog: HH.ru вакансии как сигнал спроса на проектирование",
        "backlog: партнёры: риелторы, дизайнеры, юристы, кадастровые инженеры",
        "backlog: сайт / лендинги / SEO-страницы услуг",
        "backlog: +10 ещё"
      ],
      "tools": [
        "Browser Use позже",
        "Context7",
        "Firecrawl/Apify позже",
        "agents/agent1_scout/__init__.py"
      ],
      "okr": "Дать системе понятный список перспективных источников и первый следующий шаг по каждому источнику.",
      "krMetrics": [
        {
          "label": "Учтены все каналы системы",
          "current": 17,
          "target": 17,
          "unit": "каналов"
        },
        {
          "label": "Каналы первой волны разложены по агентам",
          "current": 9,
          "target": 9,
          "unit": "каналов"
        },
        {
          "label": "Planned-каналы из дашборда лектора учтены",
          "current": 8,
          "target": 8,
          "unit": "каналов"
        },
        {
          "label": "Конкурентные и рыночные источники в watchlist",
          "current": 15,
          "target": 15,
          "unit": "строк"
        },
        {
          "label": "Source cards первой волны готовы",
          "current": 0,
          "target": 9,
          "unit": "карточек"
        },
        {
          "label": "Личные каналы Яники заполнены",
          "current": 0,
          "target": 5,
          "unit": "ссылок"
        }
      ],
      "guardMetrics": [
        "0 источников переводятся в активный сбор без владельца, next_action и проверки риска",
        "0 неподтверждённых утверждений о конкурентах попадает в итоговые рекомендации"
      ],
      "skills": [
        "поиск источников",
        "анализ конкурентов",
        "анализ отзывов",
        "поиск тендерного спроса"
      ],
      "modules": [
        "Market Research Agent",
        "Competitor Analyst",
        "Source Radar",
        "Reviews/Maps Monitor",
        "Demand Signal Curator"
      ],
      "subroles": [
        {
          "name": "Market Research Agent",
          "responsibility": "рыночный спрос, сегменты, темы",
          "artifact": "SignalCard",
          "kpi": "5+ полезных сигналов перед запуском нового источника"
        },
        {
          "name": "Competitor Analyst",
          "responsibility": "конкуренты, упаковка, доказательства",
          "artifact": "competitor_note",
          "kpi": "у каждого конкурента есть ссылка, сегмент, сильная сторона и risk_notes"
        },
        {
          "name": "Source Radar",
          "responsibility": "новые каналы лидов и контента",
          "artifact": "source_signal_card",
          "kpi": "100% новых источников имеют owner_agent и next_action"
        },
        {
          "name": "Reviews/Maps Monitor",
          "responsibility": "карты, отзывы, вопросы клиентов",
          "artifact": "review_signal",
          "kpi": "отзывы превращаются в боли, FAQ и темы, без копирования"
        },
        {
          "name": "Demand Signal Curator",
          "responsibility": "отбор сигналов и handoff",
          "artifact": "handoff_recommendation",
          "kpi": "100% SignalCard имеют recommended_action, handoff_to, risk_notes"
        }
      ],
      "nextAction": "Сделать первую source card для одного выбранного источника и передать её Agent 2.",
      "exampleTask": "Следующий безопасный шаг: Сделать первую source card для одного выбранного источника и передать её Agent 2.",
      "agentFile": "agents/agent1_scout/__init__.py"
    },
    {
      "id": "a2-collector",
      "dashboardAgentId": "agent2_collector",
      "label": "Agent 2 · Collector",
      "short": "A2",
      "type": "agent",
      "department": "Сбор лидов",
      "x": 560,
      "y": 840,
      "w": 320,
      "h": 188,
      "accent": "#4DE3FF",
      "status": "queued",
      "statusLabel": "partial",
      "description": "Забирает лиды из разрешённого источника и превращает их в сырые карточки.",
      "readiness": 45,
      "krReadiness": 50,
      "stats": [
        {
          "k": "Покрытие источнико…",
          "v": "1/4 источников"
        },
        {
          "k": "subroles",
          "v": "5"
        },
        {
          "k": "skills",
          "v": "3"
        },
        {
          "k": "status",
          "v": "partial"
        }
      ],
      "responsibilities": [
        "Tender/Email Collector: почта и тендерные письма → raw_lead",
        "Marketplace Collector: Avito, Profi, Яндекс Услуги позже → marketplace_raw_lead",
        "Directory Collector: карты и каталоги позже → directory_signal",
        "Lead Normalizer: единый формат RawLead → normalized_raw_lead",
        "Duplicate Guard: дубли до передачи дальше → duplicate_decision"
      ],
      "inputs": [
        "один разрешённый источник",
        "IMAP/tender email",
        "future marketplace signals"
      ],
      "outputs": [
        "RawLead в Redis leads:raw"
      ],
      "sources": [
        "Собирает входящие лиды из разрешённых площадок первой волны.",
        "primary: Gmail tenders",
        "primary: Avito",
        "primary: Profi.ru",
        "primary: Yandex Services"
      ],
      "tools": [
        "IMAP",
        "Redis",
        "Playwright/Apify позже",
        "agents/agent2_collector/__init__.py"
      ],
      "okr": "Безопасно получить первый тестовый лид из одного источника и передать его на квалификацию.",
      "krMetrics": [
        {
          "label": "Источники сбора Agent 2 учтены",
          "current": 4,
          "target": 4,
          "unit": "каналов"
        },
        {
          "label": "Автоматизированный или проверенный сбор",
          "current": 1,
          "target": 4,
          "unit": "источников"
        },
        {
          "label": "Тестовые RawLead для покрытия Agent 2",
          "current": 1,
          "target": 4,
          "unit": "лидов"
        },
        {
          "label": "Месячный пилот сбора",
          "current": 0,
          "target": 20,
          "unit": "RawLead"
        },
        {
          "label": "Redis-передача RawLead доказана",
          "current": 1,
          "target": 1,
          "unit": "тест"
        }
      ],
      "guardMetrics": [
        "0 массовых сборов, парсингов и реальных площадок без отдельного подтверждения",
        "дубли должны отсекаться до передачи дальше; целевой порог дублей после фильтра — 0"
      ],
      "skills": [
        "разбор писем",
        "разметка источника",
        "нормализация данных"
      ],
      "modules": [
        "Tender/Email Collector",
        "Marketplace Collector",
        "Directory Collector",
        "Lead Normalizer",
        "Duplicate Guard"
      ],
      "subroles": [
        {
          "name": "Tender/Email Collector",
          "responsibility": "почта и тендерные письма",
          "artifact": "raw_lead",
          "kpi": "RawLead создаётся без потери source и raw_text"
        },
        {
          "name": "Marketplace Collector",
          "responsibility": "Avito, Profi, Яндекс Услуги позже",
          "artifact": "marketplace_raw_lead",
          "kpi": "один источник за раз, не все платформы сразу"
        },
        {
          "name": "Directory Collector",
          "responsibility": "карты и каталоги позже",
          "artifact": "directory_signal",
          "kpi": "только разрешённые публичные сигналы"
        },
        {
          "name": "Lead Normalizer",
          "responsibility": "единый формат RawLead",
          "artifact": "normalized_raw_lead",
          "kpi": "100% RawLead имеют source, flow, raw_text, created_at"
        },
        {
          "name": "Duplicate Guard",
          "responsibility": "дубли до передачи дальше",
          "artifact": "duplicate_decision",
          "kpi": "явные дубли не уходят в Agent 3"
        }
      ],
      "nextAction": "Провести один безопасный тест сбора из одного источника без массового парсинга.",
      "exampleTask": "Следующий безопасный шаг: Провести один безопасный тест сбора из одного источника без массового парсинга.",
      "agentFile": "agents/agent2_collector/__init__.py"
    },
    {
      "id": "a3-processor",
      "dashboardAgentId": "agent3_processor",
      "label": "Agent 3 · Processor",
      "short": "A3",
      "type": "agent",
      "department": "Обработка и скоринг",
      "x": 1180,
      "y": 700,
      "w": 340,
      "h": 200,
      "accent": "#66F2A6",
      "status": "active",
      "statusLabel": "tested_partial",
      "description": "Очищает лид, понимает его смысл, ставит приоритет и предлагает следующий шаг.",
      "readiness": 70,
      "krReadiness": 67,
      "stats": [
        {
          "k": "Обработанные тесто…",
          "v": "1/9 лидов"
        },
        {
          "k": "subroles",
          "v": "5"
        },
        {
          "k": "skills",
          "v": "4"
        },
        {
          "k": "status",
          "v": "tested_partial"
        }
      ],
      "responsibilities": [
        "Cleaner: шум, мусор, оффтопик → clean_lead",
        "Enricher: город, объект, площадь, контакт → lead_enrichment",
        "Scorer: hot/warm/cold/off → score_result",
        "Offer/Next-Step Architect: оффер и следующий шаг → qualified_lead",
        "QA Classifier: проверка завышенного score → processor_quality_note"
      ],
      "inputs": [
        "RawLead из Redis leads:raw"
      ],
      "outputs": [
        "QualifiedLead в Redis leads:qualified"
      ],
      "sources": [
        "Не ходит наружу: принимает RawLead от Agent 2/6 и должен уметь обработать лиды из всех каналов первой волны.",
        "primary: Gmail tenders",
        "primary: Telegram chats",
        "primary: Outbound manual",
        "primary: Avito",
        "primary: Profi.ru",
        "primary: Yandex Services",
        "primary: +3 ещё",
        "backlog: после MVP обработка всех 17 каналов, а не только wave_1"
      ],
      "tools": [
        "Redis",
        "shared/llm_client.py",
        "OpenRouter/Anthropic/dry_run",
        "agents/agent3_processor/__init__.py"
      ],
      "okr": "Отделить сильные заявки от слабых и дать менеджеру понятное действие по каждому лиду.",
      "krMetrics": [
        {
          "label": "Сквозной тест лида обработан",
          "current": 1,
          "target": 1,
          "unit": "тест"
        },
        {
          "label": "Покрытие первой волны источников",
          "current": 1,
          "target": 9,
          "unit": "лидов"
        },
        {
          "label": "Режимы скоринга проверены",
          "current": 2,
          "target": 2,
          "unit": "режима"
        },
        {
          "label": "CRM-handoff проверен",
          "current": 1,
          "target": 1,
          "unit": "тест"
        },
        {
          "label": "Категории score проверены",
          "current": 1,
          "target": 4,
          "unit": "категорий"
        }
      ],
      "guardMetrics": [
        "ошибочные hot-лиды после появления реальной выборки — не выше 10%",
        "0 QualifiedLead без source, score_reason и recommended_action"
      ],
      "skills": [
        "очистка данных",
        "выделение сути",
        "скоринг лида",
        "подготовка оффера"
      ],
      "modules": [
        "Cleaner",
        "Enricher",
        "Scorer",
        "Offer/Next-Step Architect",
        "QA Classifier"
      ],
      "subroles": [
        {
          "name": "Cleaner",
          "responsibility": "шум, мусор, оффтопик",
          "artifact": "clean_lead",
          "kpi": "оффтопик не попадает в CRM"
        },
        {
          "name": "Enricher",
          "responsibility": "город, объект, площадь, контакт",
          "artifact": "lead_enrichment",
          "kpi": "доступные поля извлекаются из текста"
        },
        {
          "name": "Scorer",
          "responsibility": "hot/warm/cold/off",
          "artifact": "score_result",
          "kpi": "каждый score имеет score_reason"
        },
        {
          "name": "Offer/Next-Step Architect",
          "responsibility": "оффер и следующий шаг",
          "artifact": "qualified_lead",
          "kpi": "каждый QualifiedLead имеет recommended_action"
        },
        {
          "name": "QA Classifier",
          "responsibility": "проверка завышенного score",
          "artifact": "processor_quality_note",
          "kpi": "после выборки ошибочные hot-лиды не выше 10%"
        }
      ],
      "nextAction": "Закрыть полный handoff: Agent 3 -> Agent 5 на одном тестовом лиде.",
      "exampleTask": "Следующий безопасный шаг: Закрыть полный handoff: Agent 3 -> Agent 5 на одном тестовом лиде.",
      "agentFile": "agents/agent3_processor/__init__.py"
    },
    {
      "id": "a4-publisher",
      "dashboardAgentId": "agent4_publisher",
      "label": "Agent 4 · Publisher",
      "short": "A4",
      "type": "agent",
      "department": "Контент и доверие",
      "x": 1180,
      "y": 1040,
      "w": 340,
      "h": 200,
      "accent": "#F6C85F",
      "status": "waiting",
      "statusLabel": "dry_run/manual",
      "description": "Готовит контент, который объясняет экспертизу студии и усиливает доверие.",
      "readiness": 40,
      "krReadiness": 34,
      "stats": [
        {
          "k": "Контентные поверхн…",
          "v": "5/7 поверхностей"
        },
        {
          "k": "subroles",
          "v": "6"
        },
        {
          "k": "skills",
          "v": "4"
        },
        {
          "k": "status",
          "v": "dry_run/manual"
        }
      ],
      "responsibilities": [
        "Content Strategist: рубрика, формат, этап воронки → content_brief",
        "Copywriter: черновик в стиле СИЛА Проекта → content_draft",
        "Editor: стиль, доказательства, запреты → editor_check",
        "Visual/Media Brief Creator: ТЗ на визуал, анимацию, видео позже → media_brief",
        "Approval Coordinator: согласование и правки → approval_card",
        "Content Metrics Analyst: связь постов с метриками и лидами позже → content_metric_event"
      ],
      "inputs": [
        "темы",
        "бренд",
        "контент-план",
        "approval человека"
      ],
      "outputs": [
        "черновики",
        "dry-run материалы",
        "content:published позже"
      ],
      "sources": [
        "Отвечает за каналы доверия, контентные поверхности, сайт, карты и будущие платные/органические источники.",
        "primary: Yandex Maps",
        "primary: Yandex Direct",
        "primary: Google Ads",
        "primary: VK Ads",
        "primary: Meta Ads",
        "primary: Telegram Ads",
        "primary: +3 ещё",
        "backlog: новый сайт / SEO-страницы",
        "backlog: лид-магнит ПРОВЕРКА",
        "backlog: GEO/AI visibility",
        "backlog: Reels/shorts radar",
        "backlog: ROMI по контенту"
      ],
      "tools": [
        "shared/llm_client.py -> OpenRouter/Anthropic/dry_run",
        "imagegen/OpenAI image позже",
        "MAX/PostMyPost позже",
        "agents/agent4_publisher/__init__.py"
      ],
      "okr": "Стабильно готовить черновики контента и материалы доверия без автопубликации.",
      "krMetrics": [
        {
          "label": "Контентные поверхности учтены",
          "current": 5,
          "target": 7,
          "unit": "поверхностей"
        },
        {
          "label": "Черновики первой недели",
          "current": 0,
          "target": 5,
          "unit": "материалов"
        },
        {
          "label": "Ядро месячного плана",
          "current": 0,
          "target": 20,
          "unit": "тем"
        },
        {
          "label": "Полный адаптированный план после MVP",
          "current": 0,
          "target": 52,
          "unit": "материала"
        },
        {
          "label": "Поля согласования в шаблоне",
          "current": 3,
          "target": 3,
          "unit": "поля"
        }
      ],
      "guardMetrics": [
        "0 реальных публикаций без отдельного подтверждения Яники",
        "0 материалов с персональными данными или обещаниями без доказательств",
        "стоимость генерации должна быть заполнена у 100% материалов перед публикацией"
      ],
      "skills": [
        "копирайтинг",
        "SEO-темы",
        "визуальные промпты",
        "UTM-логика"
      ],
      "modules": [
        "Content Strategist",
        "Copywriter",
        "Editor",
        "Visual/Media Brief Creator",
        "Approval Coordinator",
        "Content Metrics Analyst"
      ],
      "subroles": [
        {
          "name": "Content Strategist",
          "responsibility": "рубрика, формат, этап воронки",
          "artifact": "content_brief",
          "kpi": "у каждого материала есть формат, воронка и канал"
        },
        {
          "name": "Copywriter",
          "responsibility": "черновик в стиле СИЛА Проекта",
          "artifact": "content_draft",
          "kpi": "посты не повторяют одну структуру подряд"
        },
        {
          "name": "Editor",
          "responsibility": "стиль, доказательства, запреты",
          "artifact": "editor_check",
          "kpi": "0 неподтверждённых обещаний и общих рекламных фраз"
        },
        {
          "name": "Visual/Media Brief Creator",
          "responsibility": "ТЗ на визуал, анимацию, видео позже",
          "artifact": "media_brief",
          "kpi": "медиа только как ТЗ или dry-run до approval"
        },
        {
          "name": "Approval Coordinator",
          "responsibility": "согласование и правки",
          "artifact": "approval_card",
          "kpi": "100% материалов имеют статус, стоимость, причину перегенерации при правках"
        },
        {
          "name": "Content Metrics Analyst",
          "responsibility": "связь постов с метриками и лидами позже",
          "artifact": "content_metric_event",
          "kpi": "каждый опубликованный материал позже получает content_metric_event"
        }
      ],
      "nextAction": "Держать публикации в dry-run и позже связать контент-события с аналитикой Agent 5.",
      "exampleTask": "Следующий безопасный шаг: Держать публикации в dry-run и позже связать контент-события с аналитикой Agent 5.",
      "agentFile": "agents/agent4_publisher/__init__.py"
    },
    {
      "id": "a5-crm",
      "dashboardAgentId": "agent5_crm",
      "label": "Agent 5 · CRM",
      "short": "A5",
      "type": "agent",
      "department": "CRM и аналитика",
      "x": 1820,
      "y": 700,
      "w": 340,
      "h": 200,
      "accent": "#66F2A6",
      "status": "active",
      "statusLabel": "tested",
      "description": "Создаёт лид в CRM, отправляет уведомление и считает результативность каналов.",
      "readiness": 80,
      "krReadiness": 81,
      "stats": [
        {
          "k": "Каналы в сквозной …",
          "v": "17/17 каналов"
        },
        {
          "k": "subroles",
          "v": "6"
        },
        {
          "k": "skills",
          "v": "4"
        },
        {
          "k": "status",
          "v": "tested"
        }
      ],
      "responsibilities": [
        "CRM Router: Bitrix24 payload для лида/сделки → crm_payload_preview",
        "Notifier: уведомление человека → notification_event",
        "Attribution Agent: first_touch, last_touch, канал, UTM → attribution_record",
        "ROMI Reporter: CPL, CAC, profit, ROMI → channel_report",
        "CRM Hygiene Analyst: дубли, пустые поля, слабые карточки → crm_hygiene_report",
        "Weekly Digest Owner: недельный итог системы позже → weekly_digest"
      ],
      "inputs": [
        "QualifiedLead",
        "OutreachLead",
        "content:published"
      ],
      "outputs": [
        "Bitrix24 лид",
        "Telegram alert",
        "CSV/ROMI отчёт"
      ],
      "sources": [
        "Считает всю сквозную аналитику по 17 каналам и принимает CRM-события.",
        "primary: Gmail tenders",
        "primary: Telegram chats",
        "primary: Outbound manual",
        "primary: Avito",
        "primary: Profi.ru",
        "primary: Yandex Services",
        "primary: +11 ещё",
        "owner: Referrals",
        "owner: Old inquiries",
        "backlog: visit_count",
        "backlog: visitor_id",
        "backlog: CR visit->deal",
        "backlog: ROMI по контенту"
      ],
      "tools": [
        "Bitrix24 REST",
        "Telegram Bot API",
        "CSV",
        "Supabase/Sheets позже",
        "agents/agent5_crm/__init__.py"
      ],
      "okr": "Довести квалифицированный лид до CRM, уведомления и отчёта по результативности.",
      "krMetrics": [
        {
          "label": "Каналы в сквозной аналитике",
          "current": 17,
          "target": 17,
          "unit": "каналов"
        },
        {
          "label": "Каналы первой волны отслеживаются",
          "current": 9,
          "target": 9,
          "unit": "каналов"
        },
        {
          "label": "Сквозной CRM-тест закрыт",
          "current": 1,
          "target": 1,
          "unit": "тест"
        },
        {
          "label": "CRM-цепочка урока 5 покрыта",
          "current": 5,
          "target": 6,
          "unit": "шагов"
        },
        {
          "label": "Тестовые Bitrix24-создания",
          "current": 4,
          "target": 3,
          "unit": "теста"
        },
        {
          "label": "Метрика лектора CR visit->deal",
          "current": 0,
          "target": 1,
          "unit": "метрика"
        }
      ],
      "guardMetrics": [
        "0 секретов, webhook и token-значений в отчётах",
        "0 реальных клиентских данных в тестовых лидах",
        "доля лидов без source в реальной работе должна быть не выше 10%"
      ],
      "skills": [
        "Bitrix24",
        "воронка CRM",
        "сквозная аналитика",
        "отчёты"
      ],
      "modules": [
        "CRM Router",
        "Notifier",
        "Attribution Agent",
        "ROMI Reporter",
        "CRM Hygiene Analyst",
        "Weekly Digest Owner"
      ],
      "subroles": [
        {
          "name": "CRM Router",
          "responsibility": "Bitrix24 payload для лида/сделки",
          "artifact": "crm_payload_preview",
          "kpi": "payload создаётся локально до реальной отправки"
        },
        {
          "name": "Notifier",
          "responsibility": "уведомление человека",
          "artifact": "notification_event",
          "kpi": "уведомления без секретов и лишних персональных данных"
        },
        {
          "name": "Attribution Agent",
          "responsibility": "first_touch, last_touch, канал, UTM",
          "artifact": "attribution_record",
          "kpi": "100% тестовых лидов имеют first_touch_channel и last_touch_channel"
        },
        {
          "name": "ROMI Reporter",
          "responsibility": "CPL, CAC, profit, ROMI",
          "artifact": "channel_report",
          "kpi": "spend -> leads -> deals -> revenue -> profit -> ROMI"
        },
        {
          "name": "CRM Hygiene Analyst",
          "responsibility": "дубли, пустые поля, слабые карточки",
          "artifact": "crm_hygiene_report",
          "kpi": "дубли и пустые поля попадают в очередь ручной чистки"
        },
        {
          "name": "Weekly Digest Owner",
          "responsibility": "недельный итог системы позже",
          "artifact": "weekly_digest",
          "kpi": "лиды, CRM, контент, ROMI и блокеры раз в неделю"
        }
      ],
      "nextAction": "Закрыть один сквозной тест: квалифицированный лид -> Bitrix24 -> Telegram -> отчёт.",
      "exampleTask": "Следующий безопасный шаг: Закрыть один сквозной тест: квалифицированный лид -> Bitrix24 -> Telegram -> отчёт.",
      "agentFile": "agents/agent5_crm/__init__.py"
    },
    {
      "id": "a6-outreach",
      "dashboardAgentId": "agent6_outreach",
      "label": "Agent 6 · Outreach",
      "short": "A6",
      "type": "agent",
      "department": "Первое касание",
      "x": 560,
      "y": 1140,
      "w": 320,
      "h": 188,
      "accent": "#F6C85F",
      "status": "blocked",
      "statusLabel": "planned/locked",
      "description": "Готовит аккуратное первое касание, но не отправляет его без согласования человека.",
      "readiness": 25,
      "krReadiness": 40,
      "stats": [
        {
          "k": "Outreach-источники…",
          "v": "0/2 источников"
        },
        {
          "k": "subroles",
          "v": "6"
        },
        {
          "k": "skills",
          "v": "4"
        },
        {
          "k": "status",
          "v": "planned/locked"
        }
      ],
      "responsibilities": [
        "Social Listening Monitor: релевантные обсуждения → outreach_candidate",
        "Candidate Qualifier: риск спама и релевантность → outreach_decision",
        "Reply Draft Writer: человеческий ответ → reply_draft",
        "Approval Gatekeeper: запрет отправки без человека → approval_required",
        "Outreach Sender: отправка после approval → sent_outreach_event",
        "Dialog Converter: интерес -> OutreachLead → outreach_lead"
      ],
      "inputs": [
        "Telegram/VK/forum/MAX/TenChat/Yandex Q candidates",
        "approval человека"
      ],
      "outputs": [
        "approved reply",
        "OutreachLead",
        "интерес в Agent 5"
      ],
      "sources": [
        "Готовит первое касание по диалогам и ручному outbound, но ничего не отправляет без approval.",
        "primary: Telegram chats",
        "primary: Outbound manual"
      ],
      "tools": [
        "Telethon",
        "Telegram Bot API",
        "VK API позже",
        "MAX/TenChat позже",
        "agents/agent6_outreach/__init__.py"
      ],
      "okr": "Подготовить безопасный первый контакт по найденному диалогу, но отправлять только после одобрения.",
      "krMetrics": [
        {
          "label": "Outreach-источники первой волны учтены",
          "current": 2,
          "target": 2,
          "unit": "источника"
        },
        {
          "label": "Кандидаты для ручной проверки",
          "current": 0,
          "target": 10,
          "unit": "кандидатов"
        },
        {
          "label": "Черновики первых ответов",
          "current": 0,
          "target": 5,
          "unit": "ответов"
        },
        {
          "label": "Outreach -> CRM тест",
          "current": 0,
          "target": 1,
          "unit": "тест"
        },
        {
          "label": "Реальные отправки до approval",
          "current": 0,
          "target": 0,
          "unit": "сообщений"
        }
      ],
      "guardMetrics": [
        "0 сообщений без approval",
        "после разрешения пилотный лимит — не больше 5 отправок в день",
        "0 жалоб/спам-сигналов"
      ],
      "skills": [
        "поиск диалогов",
        "текст первого касания",
        "согласование",
        "продажный диалог"
      ],
      "modules": [
        "Social Listening Monitor",
        "Candidate Qualifier",
        "Reply Draft Writer",
        "Approval Gatekeeper",
        "Outreach Sender",
        "Dialog Converter"
      ],
      "subroles": [
        {
          "name": "Social Listening Monitor",
          "responsibility": "релевантные обсуждения",
          "artifact": "outreach_candidate",
          "kpi": "кандидат не создаётся без URL/контекста и причины релевантности"
        },
        {
          "name": "Candidate Qualifier",
          "responsibility": "риск спама и релевантность",
          "artifact": "outreach_decision",
          "kpi": "спорные кандидаты идут в escalation-to-yana"
        },
        {
          "name": "Reply Draft Writer",
          "responsibility": "человеческий ответ",
          "artifact": "reply_draft",
          "kpi": "ответ полезный, не спамный, без давления"
        },
        {
          "name": "Approval Gatekeeper",
          "responsibility": "запрет отправки без человека",
          "artifact": "approval_required",
          "kpi": "0 реальных отправок без approval"
        },
        {
          "name": "Outreach Sender",
          "responsibility": "отправка после approval",
          "artifact": "sent_outreach_event",
          "kpi": "после разрешения не больше 5 отправок в день на пилоте"
        },
        {
          "name": "Dialog Converter",
          "responsibility": "интерес -> OutreachLead",
          "artifact": "outreach_lead",
          "kpi": "заинтересованный ответ уходит в Agent 5"
        }
      ],
      "nextAction": "Сначала сделать approval-flow на черновике без реальной отправки сообщений.",
      "exampleTask": "Следующий безопасный шаг: Сначала сделать approval-flow на черновике без реальной отправки сообщений.",
      "agentFile": "agents/agent6_outreach/__init__.py"
    }
  ],
  "services": [
    {
      "id": "svc-scheduler",
      "label": "Technical Scheduler",
      "type": "module",
      "x": 160,
      "y": 1300,
      "w": 210,
      "h": 86,
      "accent": "#8E9AAA",
      "status": "blocked",
      "statusLabel": "Locked",
      "description": "Технический запускатель. В MVP не запускается до проверки блокеров.",
      "responsibilities": [
        "Расписание периодических задач",
        "Технический запуск, не бизнес-оркестратор"
      ],
      "inputs": [
        "Cron config"
      ],
      "outputs": [
        "scheduled jobs"
      ],
      "tools": [
        "orchestrator/scheduler.py"
      ]
    },
    {
      "id": "svc-redis",
      "label": "Redis Queues",
      "type": "module",
      "x": 390,
      "y": 1300,
      "w": 210,
      "h": 86,
      "accent": "#4DE3FF",
      "status": "idle",
      "statusLabel": "Not called now",
      "description": "Очереди для передачи RawLead, QualifiedLead, content drafts и approval cards.",
      "responsibilities": [
        "Передача артефактов между агентами",
        "Очереди MVP"
      ],
      "inputs": [
        "RawLead",
        "QualifiedLead",
        "Content Draft"
      ],
      "outputs": [
        "Queue events"
      ],
      "tools": [
        "Redis",
        "shared/queue"
      ]
    },
    {
      "id": "svc-sources",
      "label": "Source Registry",
      "type": "module",
      "x": 620,
      "y": 1300,
      "w": 210,
      "h": 86,
      "accent": "#4DE3FF",
      "status": "active",
      "description": "Реестр 17 каналов, волн, владельцев и UTM-логики.",
      "responsibilities": [
        "Хранение каналов",
        "Связь канала с owner_agent",
        "Волны запуска"
      ],
      "inputs": [
        "channel-registry-mvp.csv"
      ],
      "outputs": [
        "source_map"
      ],
      "tools": [
        "content/library/sources/channel-registry-mvp.csv"
      ]
    },
    {
      "id": "svc-checker",
      "label": "Checker / QA",
      "type": "module",
      "x": 850,
      "y": 1300,
      "w": 210,
      "h": 86,
      "accent": "#F6C85F",
      "status": "active",
      "description": "Проверяет, что реальные файлы соответствуют схеме агентов, OKR и dashboard.",
      "responsibilities": [
        "Сверка файлов",
        "Проверка OKR",
        "Отчёт по пропускам"
      ],
      "inputs": [
        "agent contracts"
      ],
      "outputs": [
        "checker report"
      ],
      "tools": [
        "scripts/check_agent_okr_contract.py"
      ]
    },
    {
      "id": "svc-report",
      "label": "REPORT.md Memory",
      "type": "module",
      "x": 1080,
      "y": 1300,
      "w": 210,
      "h": 86,
      "accent": "#A6B0FF",
      "status": "active",
      "description": "Память проекта: что сделано, что проверено, что дальше.",
      "responsibilities": [
        "История работ",
        "Следующий шаг",
        "Safety decisions"
      ],
      "inputs": [
        "agent-result",
        "task-handoff"
      ],
      "outputs": [
        "REPORT.md update"
      ],
      "tools": [
        "REPORT.md",
        "tasks/session-notes.md"
      ]
    },
    {
      "id": "svc-dashboard",
      "label": "Dashboard Reports",
      "type": "module",
      "x": 1310,
      "y": 1300,
      "w": 210,
      "h": 86,
      "accent": "#66F2A6",
      "status": "active",
      "description": "Локальные отчёты по агентам, сценариям, каналам и CRM.",
      "responsibilities": [
        "Снимок состояния",
        "HTML/MD/JSON отчёты",
        "Сценарии"
      ],
      "inputs": [
        "agent facts",
        "source facts",
        "scenario checks"
      ],
      "outputs": [
        "agent_dashboard.json"
      ],
      "tools": [
        "scripts/build_agent_dashboard.py",
        "data/reports/agent_dashboard.json"
      ]
    },
    {
      "id": "svc-visual-api",
      "label": "Local Visual API",
      "type": "module",
      "x": 1540,
      "y": 1300,
      "w": 210,
      "h": 86,
      "accent": "#66F2A6",
      "status": "active",
      "description": "Новый backend для визуализации. Только читает локальные отчёты и отдаёт их frontend.",
      "responsibilities": [
        "Serve frontend",
        "Expose /api/dashboard",
        "Generate runtime data.js"
      ],
      "inputs": [
        "data/reports/agent_dashboard.json"
      ],
      "outputs": [
        "window.AGENT_DATA",
        "JSON API"
      ],
      "tools": [
        "backend/agent_dashboard_api/server.py",
        "frontend/agent-system-visual"
      ]
    }
  ],
  "sources": [
    {
      "id": "src-wave1",
      "label": "Wave 1 · Первая волна",
      "type": "source",
      "x": 140,
      "y": 480,
      "w": 240,
      "h": 218,
      "accent": "#4DE3FF",
      "status": "active",
      "description": "Каналы MVP, которые проверяются первыми.",
      "list": [
        "Gmail tenders",
        "Telegram chats",
        "Outbound manual",
        "Avito",
        "Profi.ru",
        "Yandex Services",
        "Yandex Maps",
        "Referrals",
        "Old inquiries"
      ]
    },
    {
      "id": "src-wave2",
      "label": "Wave 2 · Платный охват",
      "type": "source",
      "x": 140,
      "y": 760,
      "w": 240,
      "h": 168,
      "accent": "#F6C85F",
      "status": "queued",
      "description": "Планируемые каналы после MVP.",
      "list": [
        "Yandex Direct",
        "VK Ads",
        "Telegram Ads",
        "Dzen and RSY",
        "Influencer TG",
        "SEO organic"
      ]
    },
    {
      "id": "src-wave3",
      "label": "Wave 3 · Внешние сети",
      "type": "source",
      "x": 140,
      "y": 980,
      "w": 240,
      "h": 100,
      "accent": "#A6B0FF",
      "status": "idle",
      "description": "Отложенные каналы для более поздней проверки.",
      "list": [
        "Google Ads",
        "Meta Ads"
      ]
    },
    {
      "id": "src-watchlist",
      "label": "Competitor Watchlist",
      "type": "source",
      "x": 140,
      "y": 220,
      "w": 240,
      "h": 116,
      "accent": "#8E9AAA",
      "status": "idle",
      "description": "Конкуренты, каналы Яники и backlog-источники для Agent 1.",
      "list": [
        "15 competitors",
        "5 Yanika channels",
        "16 backlog sources",
        "12 lecture growth sources"
      ]
    }
  ],
  "artifacts": [
    {
      "id": "art-source",
      "label": "Source Card",
      "type": "artifact",
      "x": 880,
      "y": 320,
      "w": 180,
      "h": 64,
      "accent": "#4DE3FF"
    },
    {
      "id": "art-signal",
      "label": "Signal Card",
      "type": "artifact",
      "x": 880,
      "y": 400,
      "w": 180,
      "h": 64,
      "accent": "#4DE3FF"
    },
    {
      "id": "art-intake",
      "label": "Intake Card",
      "type": "artifact",
      "x": 880,
      "y": 780,
      "w": 180,
      "h": 64,
      "accent": "#4DE3FF"
    },
    {
      "id": "art-raw",
      "label": "RawLead",
      "type": "artifact",
      "x": 880,
      "y": 870,
      "w": 180,
      "h": 64,
      "accent": "#4DE3FF"
    },
    {
      "id": "art-qualified",
      "label": "QualifiedLead",
      "type": "artifact",
      "x": 1560,
      "y": 700,
      "w": 180,
      "h": 64,
      "accent": "#66F2A6"
    },
    {
      "id": "art-score",
      "label": "Score & Reason",
      "type": "artifact",
      "x": 1560,
      "y": 780,
      "w": 180,
      "h": 64,
      "accent": "#66F2A6"
    },
    {
      "id": "art-action",
      "label": "Recommended Action",
      "type": "artifact",
      "x": 1560,
      "y": 860,
      "w": 180,
      "h": 64,
      "accent": "#66F2A6"
    },
    {
      "id": "art-content-brief",
      "label": "Content Brief",
      "type": "artifact",
      "x": 1560,
      "y": 1000,
      "w": 180,
      "h": 64,
      "accent": "#F6C85F"
    },
    {
      "id": "art-approval",
      "label": "Approval Card",
      "type": "artifact",
      "x": 1560,
      "y": 1080,
      "w": 180,
      "h": 64,
      "accent": "#F6C85F"
    },
    {
      "id": "art-draft",
      "label": "Content Draft",
      "type": "artifact",
      "x": 1560,
      "y": 1160,
      "w": 180,
      "h": 64,
      "accent": "#F6C85F"
    },
    {
      "id": "art-publication",
      "label": "Manual Publication",
      "type": "artifact",
      "x": 1560,
      "y": 1240,
      "w": 180,
      "h": 64,
      "accent": "#F6C85F"
    },
    {
      "id": "art-crm-preview",
      "label": "CRM Payload Preview",
      "type": "artifact",
      "x": 2200,
      "y": 500,
      "w": 180,
      "h": 64,
      "accent": "#66F2A6"
    },
    {
      "id": "art-bitrix",
      "label": "Bitrix24 Lead",
      "type": "artifact",
      "x": 2200,
      "y": 580,
      "w": 180,
      "h": 64,
      "accent": "#66F2A6"
    },
    {
      "id": "art-bitrix-deal",
      "label": "Bitrix24 Deal",
      "type": "artifact",
      "x": 2200,
      "y": 660,
      "w": 180,
      "h": 64,
      "accent": "#66F2A6"
    },
    {
      "id": "art-tg",
      "label": "Telegram Alert",
      "type": "artifact",
      "x": 2200,
      "y": 740,
      "w": 180,
      "h": 64,
      "accent": "#66F2A6"
    },
    {
      "id": "art-romi",
      "label": "ROMI Report",
      "type": "artifact",
      "x": 2200,
      "y": 820,
      "w": 180,
      "h": 64,
      "accent": "#66F2A6"
    },
    {
      "id": "art-human",
      "label": "Human Next Step",
      "type": "artifact",
      "x": 2200,
      "y": 900,
      "w": 180,
      "h": 64,
      "accent": "#F6C85F"
    },
    {
      "id": "art-costs",
      "label": "Channel Costs",
      "type": "artifact",
      "x": 2200,
      "y": 980,
      "w": 180,
      "h": 64,
      "accent": "#A6B0FF"
    },
    {
      "id": "art-facts",
      "label": "Channel Facts",
      "type": "artifact",
      "x": 2200,
      "y": 1060,
      "w": 180,
      "h": 64,
      "accent": "#A6B0FF"
    },
    {
      "id": "art-dashboard",
      "label": "Agent Dashboard",
      "type": "artifact",
      "x": 2200,
      "y": 1300,
      "w": 180,
      "h": 64,
      "accent": "#66F2A6"
    },
    {
      "id": "art-report",
      "label": "REPORT.md Memory",
      "type": "artifact",
      "x": 1660,
      "y": 230,
      "w": 180,
      "h": 64,
      "accent": "#A6B0FF"
    },
    {
      "id": "art-checker",
      "label": "Checker Report",
      "type": "artifact",
      "x": 880,
      "y": 230,
      "w": 180,
      "h": 64,
      "accent": "#F6C85F"
    },
    {
      "id": "art-outreach",
      "label": "OutreachLead",
      "type": "artifact",
      "x": 880,
      "y": 1180,
      "w": 180,
      "h": 64,
      "accent": "#F6C85F"
    },
    {
      "id": "art-content-event",
      "label": "Content Metric Event",
      "type": "artifact",
      "x": 1760,
      "y": 1240,
      "w": 180,
      "h": 64,
      "accent": "#F6C85F"
    },
    {
      "id": "art-channel-registry-row",
      "label": "channel registry row",
      "type": "artifact",
      "x": 1980,
      "y": 1400,
      "w": 180,
      "h": 64,
      "accent": "#8E9AAA"
    },
    {
      "id": "art-channel-cost-row",
      "label": "channel cost row",
      "type": "artifact",
      "x": 1980,
      "y": 1476,
      "w": 180,
      "h": 64,
      "accent": "#8E9AAA"
    },
    {
      "id": "art-channel-fact-row",
      "label": "channel fact row",
      "type": "artifact",
      "x": 1980,
      "y": 1552,
      "w": 180,
      "h": 64,
      "accent": "#8E9AAA"
    },
    {
      "id": "art-channel-report",
      "label": "channel report",
      "type": "artifact",
      "x": 1980,
      "y": 1628,
      "w": 180,
      "h": 64,
      "accent": "#8E9AAA"
    },
    {
      "id": "art-channel-decision",
      "label": "channel decision",
      "type": "artifact",
      "x": 1980,
      "y": 1704,
      "w": 180,
      "h": 64,
      "accent": "#8E9AAA"
    }
  ],
  "safety": [
    {
      "id": "lock-scheduler_locked",
      "label": "Scheduler locked",
      "reason": "scheduler_locked"
    },
    {
      "id": "lock-mass_collection_locked",
      "label": "Mass collection locked",
      "reason": "mass_collection_locked"
    },
    {
      "id": "lock-real_publish_locked",
      "label": "Real publish locked",
      "reason": "real_publish_locked"
    },
    {
      "id": "lock-real_outreach_locked",
      "label": "Real outreach locked",
      "reason": "real_outreach_locked"
    },
    {
      "id": "lock-secrets",
      "label": "Secrets hidden",
      "reason": "values are never shown"
    },
    {
      "id": "lock-agent7",
      "label": "No Agent 7",
      "reason": "checker is a service module, not a new agent"
    },
    {
      "id": "lock-не-создавать-agent-7",
      "label": "не создавать Agent 7",
      "reason": "forbidden by scenario contract"
    },
    {
      "id": "lock-не-запускать-scheduler-без-отдельного-подтверждения",
      "label": "не запускать scheduler без отдельного подтверждения",
      "reason": "forbidden by scenario contract"
    },
    {
      "id": "lock-не-запускать-массовый-сбор",
      "label": "не запускать массовый сбор",
      "reason": "forbidden by scenario contract"
    },
    {
      "id": "lock-не-публиковать-и-не-отправлять-outreach-без-approval",
      "label": "не публиковать и не отправлять outreach без approval",
      "reason": "forbidden by scenario contract"
    },
    {
      "id": "lock-не-показывать-секреты",
      "label": "не показывать секреты",
      "reason": "forbidden by scenario contract"
    }
  ],
  "agentControl": {
    "runtime_mode": "openrouter_free_test",
    "live_llm_enabled": true,
    "default_provider": "openrouter",
    "routes": [
      {
        "key": "default_free",
        "label": "DeepSeek Flash / free",
        "task": "default_free",
        "model": "deepseek/deepseek-v4-flash:free",
        "provider": "openrouter",
        "purpose": "Недорогие обычные ответы агентов и простые проверки.",
        "status": "configured_route"
      },
      {
        "key": "agent_control",
        "label": "Agent control / OpenRouter free",
        "task": "agent_control",
        "model": "deepseek/deepseek-v4-flash:free",
        "provider": "openrouter",
        "purpose": "Управление агентами, постановка задач, маршрутизация команд.",
        "status": "configured_route"
      },
      {
        "key": "development",
        "label": "Development / OpenRouter free",
        "task": "development",
        "model": "deepseek/deepseek-v4-flash:free",
        "provider": "openrouter",
        "purpose": "Разработка, архитектура, сложный дебаг и code review.",
        "status": "configured_route"
      },
      {
        "key": "marketing",
        "label": "Marketing / OpenRouter free",
        "task": "marketing",
        "model": "deepseek/deepseek-v4-flash:free",
        "provider": "openrouter",
        "purpose": "Маркетинговые тексты, посты, офферы и контентные черновики.",
        "status": "configured_route"
      },
      {
        "key": "knowledge",
        "label": "Knowledge / OpenRouter free",
        "task": "knowledge",
        "model": "deepseek/deepseek-v4-flash:free",
        "provider": "openrouter",
        "purpose": "Ответы поверх базы знаний после retrieval/embedding-поиска.",
        "status": "configured_route"
      },
      {
        "key": "transcription",
        "label": "Whisper",
        "task": "transcription",
        "model": "whisper-1",
        "provider": "local",
        "purpose": "Расшифровка голосовых команд пользователя.",
        "status": "route_only_not_called"
      },
      {
        "key": "image",
        "label": "Kling / Nano Banana image route",
        "task": "image",
        "model": "google/gemini-2.5-flash-image-preview",
        "provider": "openrouter",
        "purpose": "Картинки для вывода в чат после отдельного включения генератора.",
        "status": "route_only_not_called"
      },
      {
        "key": "embedding",
        "label": "Embedding model",
        "task": "embedding",
        "model": "gemini-embedding-001",
        "provider": "gemini",
        "purpose": "Векторный поиск по базе знаний.",
        "status": "route_only_not_called"
      }
    ],
    "safety": {
      "external_calls_by_default": false,
      "requires_flag_for_live_llm": "AGENT_CONTROL_LIVE_LLM=1",
      "secrets_policy": "API keys are never returned by this endpoint."
    }
  },
  "edges": [
    {
      "id": "e-wl-a1",
      "source": "src-watchlist",
      "target": "a1-scout",
      "type": "hierarchy",
      "label": "watchlist",
      "animated": false
    },
    {
      "id": "e-w1-a1",
      "source": "src-wave1",
      "target": "a1-scout",
      "type": "handoff",
      "label": "signals",
      "animated": false
    },
    {
      "id": "e-w1-a2",
      "source": "src-wave1",
      "target": "a2-collector",
      "type": "handoff",
      "label": "leads",
      "animated": false
    },
    {
      "id": "e-w1-a6",
      "source": "src-wave1",
      "target": "a6-outreach",
      "type": "handoff",
      "label": "chats",
      "animated": false
    },
    {
      "id": "e-w2-a4",
      "source": "src-wave2",
      "target": "a4-publisher",
      "type": "handoff",
      "label": "content/ads",
      "animated": false
    },
    {
      "id": "e-w3-a4",
      "source": "src-wave3",
      "target": "a4-publisher",
      "type": "hierarchy",
      "label": "",
      "animated": false
    },
    {
      "id": "e-orch-a1-scout",
      "source": "orchestrator",
      "target": "a1-scout",
      "type": "hierarchy",
      "label": "",
      "animated": false
    },
    {
      "id": "e-orch-a2-collector",
      "source": "orchestrator",
      "target": "a2-collector",
      "type": "hierarchy",
      "label": "",
      "animated": false
    },
    {
      "id": "e-orch-a3-processor",
      "source": "orchestrator",
      "target": "a3-processor",
      "type": "hierarchy",
      "label": "",
      "animated": false
    },
    {
      "id": "e-orch-a4-publisher",
      "source": "orchestrator",
      "target": "a4-publisher",
      "type": "hierarchy",
      "label": "",
      "animated": false
    },
    {
      "id": "e-orch-a5-crm",
      "source": "orchestrator",
      "target": "a5-crm",
      "type": "hierarchy",
      "label": "",
      "animated": false
    },
    {
      "id": "e-orch-a6-outreach",
      "source": "orchestrator",
      "target": "a6-outreach",
      "type": "hierarchy",
      "label": "",
      "animated": false
    },
    {
      "id": "e-agent-map-1",
      "source": "a1-scout",
      "target": "a2-collector",
      "type": "handoff",
      "label": "source card",
      "animated": true
    },
    {
      "id": "e-agent-map-2",
      "source": "a1-scout",
      "target": "a4-publisher",
      "type": "handoff",
      "label": "боли, темы, конкуренты",
      "animated": true
    },
    {
      "id": "e-agent-map-3",
      "source": "a1-scout",
      "target": "a5-crm",
      "type": "handoff",
      "label": "каналы для аналитики",
      "animated": true
    },
    {
      "id": "e-agent-map-4",
      "source": "a2-collector",
      "target": "a3-processor",
      "type": "handoff",
      "label": "RawLead -> leads:raw",
      "animated": true
    },
    {
      "id": "e-agent-map-5",
      "source": "a3-processor",
      "target": "a5-crm",
      "type": "handoff",
      "label": "QualifiedLead -> leads:qualified",
      "animated": true
    },
    {
      "id": "e-agent-map-6",
      "source": "a4-publisher",
      "target": "a5-crm",
      "type": "handoff",
      "label": "content_published -> content:published",
      "animated": true
    },
    {
      "id": "e-agent-map-7",
      "source": "a6-outreach",
      "target": "a5-crm",
      "type": "handoff",
      "label": "OutreachLead -> leads:outreach",
      "animated": true
    },
    {
      "id": "e-a1-source",
      "source": "a1-scout",
      "target": "art-source",
      "type": "artifact",
      "label": "source card",
      "animated": false
    },
    {
      "id": "e-a1-signal",
      "source": "a1-scout",
      "target": "art-signal",
      "type": "artifact",
      "label": "signal card",
      "animated": false
    },
    {
      "id": "e-source-a2",
      "source": "art-source",
      "target": "a2-collector",
      "type": "handoff",
      "label": "source card",
      "animated": false
    },
    {
      "id": "e-signal-a4",
      "source": "art-signal",
      "target": "a4-publisher",
      "type": "handoff",
      "label": "topics",
      "animated": false
    },
    {
      "id": "e-a2-raw",
      "source": "a2-collector",
      "target": "art-raw",
      "type": "artifact",
      "label": "raw lead",
      "animated": false
    },
    {
      "id": "e-raw-a3",
      "source": "art-raw",
      "target": "a3-processor",
      "type": "handoff",
      "label": "leads:raw",
      "animated": true
    },
    {
      "id": "e-intake-a3",
      "source": "art-intake",
      "target": "a3-processor",
      "type": "handoff",
      "label": "first inbound",
      "animated": false
    },
    {
      "id": "e-a3-qualified",
      "source": "a3-processor",
      "target": "art-qualified",
      "type": "artifact",
      "label": "qualified lead",
      "animated": false
    },
    {
      "id": "e-a3-score",
      "source": "a3-processor",
      "target": "art-score",
      "type": "artifact",
      "label": "score",
      "animated": false
    },
    {
      "id": "e-a3-action",
      "source": "a3-processor",
      "target": "art-action",
      "type": "artifact",
      "label": "next action",
      "animated": false
    },
    {
      "id": "e-qualified-a5",
      "source": "art-qualified",
      "target": "a5-crm",
      "type": "handoff",
      "label": "CRM",
      "animated": true
    },
    {
      "id": "e-a5-preview",
      "source": "a5-crm",
      "target": "art-crm-preview",
      "type": "artifact",
      "label": "payload",
      "animated": false
    },
    {
      "id": "e-a5-bitrix",
      "source": "a5-crm",
      "target": "art-bitrix",
      "type": "artifact",
      "label": "lead",
      "animated": false
    },
    {
      "id": "e-a5-deal",
      "source": "a5-crm",
      "target": "art-bitrix-deal",
      "type": "artifact",
      "label": "deal",
      "animated": false
    },
    {
      "id": "e-a5-tg",
      "source": "a5-crm",
      "target": "art-tg",
      "type": "artifact",
      "label": "alert",
      "animated": false
    },
    {
      "id": "e-a5-human",
      "source": "a5-crm",
      "target": "art-human",
      "type": "feedback",
      "label": "manual next step",
      "animated": false
    },
    {
      "id": "e-a5-romi",
      "source": "a5-crm",
      "target": "art-romi",
      "type": "artifact",
      "label": "ROMI",
      "animated": false
    },
    {
      "id": "e-a4-brief",
      "source": "a4-publisher",
      "target": "art-content-brief",
      "type": "artifact",
      "label": "brief",
      "animated": false
    },
    {
      "id": "e-a4-draft",
      "source": "a4-publisher",
      "target": "art-draft",
      "type": "artifact",
      "label": "draft",
      "animated": false
    },
    {
      "id": "e-a4-approval",
      "source": "a4-publisher",
      "target": "art-approval",
      "type": "feedback",
      "label": "approval",
      "animated": false
    },
    {
      "id": "e-a4-publish",
      "source": "a4-publisher",
      "target": "art-publication",
      "type": "artifact",
      "label": "manual publish",
      "animated": false
    },
    {
      "id": "e-content-event-a5",
      "source": "art-content-event",
      "target": "a5-crm",
      "type": "handoff",
      "label": "analytics",
      "animated": false
    },
    {
      "id": "e-a6-approval",
      "source": "a6-outreach",
      "target": "art-approval",
      "type": "feedback",
      "label": "approval",
      "animated": false
    },
    {
      "id": "e-a6-outreach",
      "source": "a6-outreach",
      "target": "art-outreach",
      "type": "artifact",
      "label": "outreach lead",
      "animated": false
    },
    {
      "id": "e-outreach-a5",
      "source": "art-outreach",
      "target": "a5-crm",
      "type": "handoff",
      "label": "interest",
      "animated": true
    },
    {
      "id": "e-costs-a5",
      "source": "art-costs",
      "target": "a5-crm",
      "type": "handoff",
      "label": "costs",
      "animated": false
    },
    {
      "id": "e-facts-a5",
      "source": "art-facts",
      "target": "a5-crm",
      "type": "handoff",
      "label": "facts",
      "animated": false
    },
    {
      "id": "e-a5-dashboard",
      "source": "a5-crm",
      "target": "art-dashboard",
      "type": "artifact",
      "label": "dashboard",
      "animated": false
    },
    {
      "id": "e-orch-report",
      "source": "orchestrator",
      "target": "art-report",
      "type": "artifact",
      "label": "memory",
      "animated": false
    },
    {
      "id": "e-orch-checker",
      "source": "orchestrator",
      "target": "art-checker",
      "type": "feedback",
      "label": "QA",
      "animated": false
    },
    {
      "id": "e-checker-orch",
      "source": "art-checker",
      "target": "orchestrator",
      "type": "feedback",
      "label": "verdict",
      "animated": false
    },
    {
      "id": "e-a5-orch",
      "source": "a5-crm",
      "target": "orchestrator",
      "type": "feedback",
      "label": "analytics",
      "animated": false
    },
    {
      "id": "e-visual-api-dashboard",
      "source": "svc-visual-api",
      "target": "art-dashboard",
      "type": "artifact",
      "label": "live data",
      "animated": false
    },
    {
      "id": "e-dashboard-api",
      "source": "art-dashboard",
      "target": "svc-visual-api",
      "type": "handoff",
      "label": "JSON",
      "animated": false
    },
    {
      "id": "e-lock-scheduler",
      "source": "svc-scheduler",
      "target": "orchestrator",
      "type": "safety",
      "label": "locked",
      "animated": false
    }
  ],
  "scenarios": [
    {
      "id": "s1",
      "label": "Первый входящий запрос",
      "summary": "site / MAX / Telegram / email → intake card → Agent 3 → Agent 5 → crm payload preview → human next step",
      "status": "OK_LOCAL_DRY_RUN_READY_FOR_MANUAL_REVIEW",
      "steps": [
        {
          "t": "site / MAX / Telegram / email",
          "node": "src-wave1"
        },
        {
          "t": "intake card",
          "node": "art-intake",
          "artifact": "art-intake"
        },
        {
          "t": "Agent 3",
          "node": "a3-processor"
        },
        {
          "t": "Agent 5",
          "node": "a5-crm"
        },
        {
          "t": "crm payload preview",
          "node": "a5-crm"
        },
        {
          "t": "human next step",
          "node": "art-human",
          "artifact": "art-human"
        }
      ],
      "path": [
        "src-wave1",
        "art-intake",
        "a3-processor",
        "a5-crm",
        "art-human"
      ]
    },
    {
      "id": "s2",
      "label": "Контент даёт лид",
      "summary": "SignalCard → content brief → content draft → approval card → content metric event → Agent 5 analytics",
      "status": "draft/manual",
      "steps": [
        {
          "t": "SignalCard",
          "node": "art-signal",
          "artifact": "art-signal"
        },
        {
          "t": "content brief",
          "node": "art-content-brief",
          "artifact": "art-content-brief"
        },
        {
          "t": "content draft",
          "node": "art-draft",
          "artifact": "art-draft"
        },
        {
          "t": "approval card",
          "node": "art-approval",
          "artifact": "art-approval"
        },
        {
          "t": "content metric event",
          "node": "art-content-event",
          "artifact": "art-content-event"
        },
        {
          "t": "Agent 5 analytics",
          "node": "a5-crm"
        }
      ],
      "path": [
        "art-signal",
        "art-content-brief",
        "art-draft",
        "art-approval",
        "art-content-event",
        "a5-crm"
      ]
    },
    {
      "id": "s3",
      "label": "Тендерный лид",
      "summary": "Gmail / IMAP tender → Agent 2 → raw lead → Agent 3 → qualified lead → Agent 5",
      "status": "partial_tested",
      "steps": [
        {
          "t": "Gmail / IMAP tender",
          "node": "src-wave1"
        },
        {
          "t": "Agent 2",
          "node": "a2-collector"
        },
        {
          "t": "raw lead",
          "node": "art-raw",
          "artifact": "art-raw"
        },
        {
          "t": "Agent 3",
          "node": "a3-processor"
        },
        {
          "t": "qualified lead",
          "node": "art-qualified",
          "artifact": "art-qualified"
        },
        {
          "t": "Agent 5",
          "node": "a5-crm"
        },
        {
          "t": "Bitrix24 / human",
          "node": "art-human",
          "artifact": "art-human"
        }
      ],
      "path": [
        "src-wave1",
        "a2-collector",
        "art-raw",
        "a3-processor",
        "art-qualified",
        "a5-crm",
        "art-human"
      ]
    },
    {
      "id": "s4",
      "label": "ROMI канала",
      "summary": "source → cost → lead → deal → revenue → profit",
      "status": "csv_mvp_exists",
      "steps": [
        {
          "t": "source",
          "node": "orchestrator"
        },
        {
          "t": "cost",
          "node": "orchestrator"
        },
        {
          "t": "lead",
          "node": "orchestrator"
        },
        {
          "t": "deal",
          "node": "orchestrator"
        },
        {
          "t": "revenue",
          "node": "orchestrator"
        },
        {
          "t": "profit",
          "node": "orchestrator"
        },
        {
          "t": "ROMI",
          "node": "orchestrator"
        },
        {
          "t": "channel decision",
          "node": "orchestrator"
        }
      ],
      "path": [
        "orchestrator"
      ]
    }
  ],
  "metricsDashboard": {
    "agent_health": {
      "agent_contract_status": "OK",
      "visual_map_status": "OK",
      "admin_dashboard_spec_status": "OK",
      "dashboard_viewer_status": "OK",
      "agents_count": 6
    },
    "system_scope": {
      "total_channels": 17,
      "wave_1_channels": 9,
      "wave_2_channels": 6,
      "wave_3_channels": 2,
      "active_channels": 3,
      "manual_channels": 6,
      "planned_channels": 8,
      "competitor_watchlist_sources": 15,
      "yanika_pending_sources": 5,
      "agent2_collection_channels": 4,
      "agent6_outreach_channels": 2,
      "content_surfaces_target": 7,
      "crm_lesson_5_chain_steps": 6
    },
    "lead_funnel": {
      "pipeline_health_test_leads": "1/1",
      "wave_1_source_coverage_target": "1/9",
      "agent2_source_coverage_target": "1/4",
      "monthly_pilot_raw_leads_target": "0/20",
      "bitrix_test_creations": "4"
    },
    "quality": {
      "score_categories_checked": "1/4",
      "llm_modes_checked": "2/2",
      "max_false_hot_rate_after_real_sample": "<=10%",
      "qualified_without_source_target": "0"
    },
    "crm_sla": {
      "lesson_5_crm_chain_covered": "5/6",
      "bitrix24_send_status": "OK",
      "telegram_send_status": "OK",
      "missing_crm_layer": "personal КП/landing status + visit_count/visitor_id"
    },
    "crm_hygiene": {
      "status": "LIMITED_AUDIT",
      "contacts": 150,
      "leads_total": 150,
      "leads_active": 0,
      "deals_total": 150,
      "contacts_without_phone_or_email": 37,
      "leads_without_phone_or_email": 24,
      "contact_phone_duplicate_groups": 2,
      "contact_email_duplicate_groups": 2,
      "lead_phone_duplicate_groups": 3,
      "lead_email_duplicate_groups": 4,
      "report_file": "data/reports/bitrix_readonly_audit.json"
    },
    "vpp_ai_manager": {
      "status": "READY",
      "scenario_count": 3,
      "enough_for_kp": 1,
      "need_missing_data": 2,
      "bitrix_dry_run_not_sent": 3,
      "report_file": "data/reports/vpp_ai_manager_dry_run.json"
    },
    "content": {
      "content_surfaces_tracked_now": "5/7",
      "first_week_drafts_target": "0/5",
      "monthly_core_topics_target": "0/20",
      "monthly_adapted_items_later": "0/52",
      "approval_fields_in_template": "3/3"
    },
    "outreach": {
      "wave_1_outreach_sources": "2/2",
      "candidate_review_target": "0/10",
      "reply_drafts_target": "0/5",
      "outreach_to_crm_test": "0/1",
      "real_sends_without_approval": 0
    },
    "romi": {
      "status": "CSV MVP есть; visit->deal из дашборда лектора ещё не закрыт",
      "report_file": "data/reports/channel_report_mvp.csv",
      "registry_channels": "17/17",
      "cost_rows": "17/17",
      "fact_rows": "17/17",
      "report_rows": "17/17",
      "missing_visit_to_deal": "visit_count + visitor_id + CR_visit_to_deal"
    },
    "safety": {
      "security_agent_status": "ACTIVE",
      "security_agent_file": "agents/Агент безопастности/AGENT_SECURITY.md",
      "locked_actions": [
        "scheduler",
        "mass_collection",
        "real_publish",
        "real_outreach"
      ],
      "secrets_visible": false
    }
  }
};
